DELIMITER $$

CREATE PROCEDURE EXCELTODB(IN MENU VARCHAR(255),IN SUBMENU VARCHAR(255),IN VIDEOCAT VARCHAR(255),IN SNO INT(11), IN TITLE VARCHAR(255),IN DESCRIPTION TEXT,IN LINK VARCHAR(255), IN DURATION VARCHAR(255))
BEGIN

DECLARE MCOUNT INT DEFAULT 0;
DECLARE MID INT;
DECLARE SMCOUNT INT DEFAULT 0;
DECLARE SMID INT;
DECLARE VCCOUNT INT DEFAULT 0;
DECLARE VCID INT;
DECLARE VLCOUNT INT DEFAULT 0;
DECLARE VLID INT;

SET FOREIGN_KEY_CHECKS = ON;

SELECT count(*) INTO MCOUNT FROM category WHERE c_name = MENU;

IF MCOUNT > 0 THEN
SELECT c_id INTO MID FROM category WHERE c_name = MENU;
ELSE
INSERT INTO category(c_name)VALUES(MENU);
SET MID = LAST_INSERT_ID();
END IF;

SELECT count(*) INTO SMCOUNT FROM sub_category WHERE sc_name = SUBMENU AND c_id = MID;

IF SMCOUNT > 0 THEN
SELECT sc_id INTO SMID FROM sub_category WHERE sc_name = SUBMENU AND c_id = MID;
ELSE
INSERT INTO sub_category(c_id,sc_name)VALUES(MID,SUBMENU);
SET SMID = LAST_INSERT_ID();
END IF;

SELECT count(*) INTO VCCOUNT FROM video_cat WHERE vc_name = VIDEOCAT AND sc_id = SMID;

IF VCCOUNT > 0 THEN
SELECT vc_id INTO VCID FROM video_cat WHERE vc_name = VIDEOCAT AND sc_id = SMID;
ELSE
INSERT INTO video_cat(sc_id,vc_name)VALUES(SMID,VIDEOCAT);
SET VCID = LAST_INSERT_ID();
END IF;

SELECT count(*) INTO VLCOUNT FROM video_list WHERE v_sno = SNO AND vc_id = VCID;

IF VLCOUNT > 0 THEN
SELECT v_id INTO VLID FROM video_list WHERE v_sno = SNO AND vc_id = VCID;
ELSE
INSERT INTO video_list(vc_id,v_sno,v_title,v_description,v_time,v_link)VALUES(VCID,SNO,TITLE,DESCRIPTION,DURATION,LINK);
SET VLID = LAST_INSERT_ID();
END IF;

SELECT VLID;

END$$

CALL EXCELTODB('Automotive','Quality','Robots',1,'test','test','test','test')

----------------------------------------------------------------------------

DELIMITER $$

CREATE PROCEDURE EXCELMENUTODB(IN MENU VARCHAR(255),IN SUBMENU VARCHAR(255))
BEGIN

DECLARE MCOUNT INT DEFAULT 0;
DECLARE MID INT;
DECLARE SMCOUNT INT DEFAULT 0;
DECLARE SMID INT;

SET FOREIGN_KEY_CHECKS = ON;

SELECT count(*) INTO MCOUNT FROM category WHERE c_name = MENU;

IF MCOUNT > 0 THEN
SELECT c_id INTO MID FROM category WHERE c_name = MENU;
ELSE
INSERT INTO category(c_name)VALUES(MENU);
SET MID = LAST_INSERT_ID();
END IF;

SELECT count(*) INTO SMCOUNT FROM sub_category WHERE sc_name = SUBMENU AND c_id = MID;

IF SMCOUNT > 0 THEN
SELECT sc_id INTO SMID FROM sub_category WHERE sc_name = SUBMENU AND c_id = MID;
ELSE
INSERT INTO sub_category(c_id,sc_name)VALUES(MID,SUBMENU);
SET SMID = LAST_INSERT_ID();
END IF;

END$$

CALL EXCELMENUTODB('Automotive','Quality')

